/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 aisoldier.gltf --transform
Author: #3D $Resource$ (https://sketchfab.com/lopuh22721)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/future-ai-soldier-f97c9b3c9dcb45cdbe7258d3ba73f0c5
Title: Future A.I Soldier
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/aisoldier-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.ME3_360_MUL_HUM_SOL_M} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/aisoldier-transformed.glb')
