/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 hand.gltf --transform
Author: SeanNicolas (https://sketchfab.com/SeanNicolas)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/robotic-hand-3e284b06bbb84d858f85f7a246cd65df
Title: Robotic Hand
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/hand-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
        <group position={[3.71, 0.56, -1.32]} rotation={[Math.PI / 2, -0.51, Math.PI / 2]} scale={0.33}>
          <mesh geometry={nodes.Sphere008_0.geometry} material={materials['Material.000']} />
          <mesh geometry={nodes.Sphere008_1.geometry} material={materials['Material.011']} />
          <mesh geometry={nodes.Sphere008_2.geometry} material={materials['Material.010']} />
        </group>
        <group position={[3.84, 0.47, -2.67]} scale={[0.06, 0.06, 0.52]}>
          <mesh geometry={nodes.Cylinder018_0.geometry} material={materials['Material.009']} />
          <mesh geometry={nodes.Cylinder018_1.geometry} material={materials['Material.010']} />
          <mesh geometry={nodes.Cylinder018_2.geometry} material={materials['Material.011']} />
        </group>
        <group position={[3.97, -0.89, -0.15]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.16, 0.16, 0.1]}>
          <mesh geometry={nodes.Cylinder017_0.geometry} material={materials['Material.009']} />
          <mesh geometry={nodes.Cylinder017_1.geometry} material={materials['Material.010']} />
          <mesh geometry={nodes.Cylinder017_2.geometry} material={materials['Material.011']} />
        </group>
        <group position={[3.9, -0.89, 0.96]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.12, 0.12, 0.08]}>
          <mesh geometry={nodes.Cylinder016_0.geometry} material={materials['Material.009']} />
          <mesh geometry={nodes.Cylinder016_1.geometry} material={materials['Material.010']} />
          <mesh geometry={nodes.Cylinder016_2.geometry} material={materials['Material.011']} />
        </group>
        <group position={[3.96, -0.89, 0.4]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.14, 0.14, 0.1]}>
          <mesh geometry={nodes.Cylinder015_0.geometry} material={materials['Material.009']} />
          <mesh geometry={nodes.Cylinder015_1.geometry} material={materials['Material.010']} />
          <mesh geometry={nodes.Cylinder015_2.geometry} material={materials['Material.011']} />
        </group>
        <group position={[4.06, -0.42, 0.72]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.17, 0.17, 0.12]}>
          <mesh geometry={nodes.Cylinder014_0.geometry} material={materials['Material.009']} />
          <mesh geometry={nodes.Cylinder014_1.geometry} material={materials['Material.010']} />
          <mesh geometry={nodes.Cylinder014_2.geometry} material={materials['Material.011']} />
        </group>
        <group position={[3.99, -0.42, 1.41]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.14, 0.14, 0.1]}>
          <mesh geometry={nodes.Cylinder013_0.geometry} material={materials['Material.009']} />
          <mesh geometry={nodes.Cylinder013_1.geometry} material={materials['Material.010']} />
          <mesh geometry={nodes.Cylinder013_2.geometry} material={materials['Material.011']} />
        </group>
        <group position={[4.07, -0.42, 0.07]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.2, 0.2, 0.13]}>
          <mesh geometry={nodes.Cylinder012_0.geometry} material={materials['Material.009']} />
          <mesh geometry={nodes.Cylinder012_1.geometry} material={materials['Material.010']} />
          <mesh geometry={nodes.Cylinder012_2.geometry} material={materials['Material.011']} />
        </group>
        <group position={[4.14, 0.1, 0.91]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.17, 0.17, 0.13]}>
          <mesh geometry={nodes.Cylinder011_0.geometry} material={materials['Material.009']} />
          <mesh geometry={nodes.Cylinder011_1.geometry} material={materials['Material.010']} />
          <mesh geometry={nodes.Cylinder011_2.geometry} material={materials['Material.011']} />
        </group>
        <group position={[4.07, 0.1, 1.64]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.14, 0.14, 0.11]}>
          <mesh geometry={nodes.Cylinder010_0.geometry} material={materials['Material.009']} />
          <mesh geometry={nodes.Cylinder010_1.geometry} material={materials['Material.010']} />
          <mesh geometry={nodes.Cylinder010_2.geometry} material={materials['Material.011']} />
        </group>
        <group position={[4.16, 0.1, 0.2]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.2, 0.2, 0.11]}>
          <mesh geometry={nodes.Cylinder009_0.geometry} material={materials['Material.009']} />
          <mesh geometry={nodes.Cylinder009_1.geometry} material={materials['Material.010']} />
          <mesh geometry={nodes.Cylinder009_2.geometry} material={materials['Material.011']} />
        </group>
        <group position={[4.11, 0.65, 0.2]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.2, 0.2, 0.11]}>
          <mesh geometry={nodes.Cylinder008_0.geometry} material={materials['Material.009']} />
          <mesh geometry={nodes.Cylinder008_1.geometry} material={materials['Material.010']} />
          <mesh geometry={nodes.Cylinder008_2.geometry} material={materials['Material.011']} />
        </group>
        <group position={[4.02, 0.65, 1.54]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.14, 0.14, 0.11]}>
          <mesh geometry={nodes.Cylinder007_0.geometry} material={materials['Material.009']} />
          <mesh geometry={nodes.Cylinder007_1.geometry} material={materials['Material.010']} />
          <mesh geometry={nodes.Cylinder007_2.geometry} material={materials['Material.011']} />
        </group>
        <group position={[4.1, 0.65, 0.85]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.17, 0.17, 0.13]}>
          <mesh geometry={nodes.Cylinder006_0.geometry} material={materials['Material.009']} />
          <mesh geometry={nodes.Cylinder006_1.geometry} material={materials['Material.010']} />
          <mesh geometry={nodes.Cylinder006_2.geometry} material={materials['Material.011']} />
        </group>
        <group position={[3.18, 1.34, -0.31]} rotation={[2.08, -1.1, 2.44]} scale={0.13}>
          <mesh geometry={nodes.Cylinder005_0.geometry} material={materials['Material.009']} />
          <mesh geometry={nodes.Cylinder005_1.geometry} material={materials['Material.010']} />
          <mesh geometry={nodes.Cylinder005_2.geometry} material={materials['Material.011']} />
        </group>
        <group position={[3.36, 1.11, -0.92]} rotation={[2.13, -1.07, 2.49]} scale={0.15}>
          <mesh geometry={nodes.Cylinder004_0.geometry} material={materials['Material.009']} />
          <mesh geometry={nodes.Cylinder004_1.geometry} material={materials['Material.010']} />
          <mesh geometry={nodes.Cylinder004_2.geometry} material={materials['Material.011']} />
        </group>
        <group position={[3.84, -0.54, -3.48]} scale={[0.12, 0.12, 1]}>
          <mesh geometry={nodes.Cylinder001_0.geometry} material={materials['Material.009']} />
          <mesh geometry={nodes.Cylinder001_1.geometry} material={materials['Material.010']} />
          <mesh geometry={nodes.Cylinder001_2.geometry} material={materials['Material.011']} />
        </group>
        <group position={[3.86, 0, -3.6]} scale={0.58}>
          <mesh geometry={nodes.Cylinder_0.geometry} material={materials['Material.009']} />
          <mesh geometry={nodes.Cylinder_1.geometry} material={materials['Material.010']} />
          <mesh geometry={nodes.Cylinder_2.geometry} material={materials['Material.011']} />
        </group>
        <group position={[3.92, -0.88, 0.92]} rotation={[0, -Math.PI / 2, 0]} scale={[0.82, 0.77, 0.82]}>
          <mesh geometry={nodes.Cube037_0.geometry} material={materials['Material.012']} />
          <mesh geometry={nodes.Cube037_1.geometry} material={materials['Material.000']} />
        </group>
        <group position={[3.92, -0.88, 0.92]} rotation={[0, -Math.PI / 2, 0]} scale={[0.82, 0.77, 0.82]}>
          <mesh geometry={nodes.Cube035_0.geometry} material={materials['Material.012']} />
          <mesh geometry={nodes.Cube035_1.geometry} material={materials['Material.009']} />
        </group>
        <group position={[4.01, -0.42, 1.36]} rotation={[0, -Math.PI / 2, 0]} scale={[0.99, 0.94, 0.99]}>
          <mesh geometry={nodes.Cube034_0.geometry} material={materials['Material.012']} />
          <mesh geometry={nodes.Cube034_1.geometry} material={materials['Material.009']} />
        </group>
        <group position={[4.01, -0.42, 1.36]} rotation={[0, -Math.PI / 2, 0]} scale={[0.99, 0.94, 0.99]}>
          <mesh geometry={nodes.Cube032_0.geometry} material={materials['Material.012']} />
          <mesh geometry={nodes.Cube032_1.geometry} material={materials['Material.000']} />
        </group>
        <group position={[4.1, 0.1, 1.6]} rotation={[0, -Math.PI / 2, 0]} scale={[1.11, 0.99, 0.99]}>
          <mesh geometry={nodes.Cube031_0.geometry} material={materials['Material.012']} />
          <mesh geometry={nodes.Cube031_1.geometry} material={materials['Material.009']} />
        </group>
        <group position={[4.1, 0.1, 1.6]} rotation={[0, -Math.PI / 2, 0]} scale={[1.11, 0.99, 0.99]}>
          <mesh geometry={nodes.Cube029_0.geometry} material={materials['Material.012']} />
          <mesh geometry={nodes.Cube029_1.geometry} material={materials['Material.000']} />
        </group>
        <group position={[4.05, 0.66, 1.49]} rotation={[0, -Math.PI / 2, 0]} scale={0.99}>
          <mesh geometry={nodes.Cube028_0.geometry} material={materials['Material.012']} />
          <mesh geometry={nodes.Cube028_1.geometry} material={materials['Material.000']} />
        </group>
        <group position={[4.05, 0.66, 1.49]} rotation={[0, -Math.PI / 2, 0]} scale={0.99}>
          <mesh geometry={nodes.Cube026_0.geometry} material={materials['Material.012']} />
          <mesh geometry={nodes.Cube026_1.geometry} material={materials['Material.009']} />
        </group>
        <group position={[3.76, 0.01, -3.94]} rotation={[0, -Math.PI / 2, 0]} scale={0.99}>
          <mesh geometry={nodes.Cube019_0.geometry} material={materials['Material.012']} />
          <mesh geometry={nodes.Cube019_1.geometry} material={materials['Material.000']} />
        </group>
        <group position={[3.81, 0, -4.03]} rotation={[0, -Math.PI / 2, 0]} scale={0.99}>
          <mesh geometry={nodes.Cube014_0.geometry} material={materials['Material.012']} />
          <mesh geometry={nodes.Cube014_1.geometry} material={materials['Material.009']} />
          <mesh geometry={nodes.Cube014_2.geometry} material={materials['Material.013']} />
        </group>
        <mesh geometry={nodes.Cylinder002_0.geometry} material={materials['Material.011']} position={[3.84, 0.56, -1.31]} rotation={[0, -Math.PI / 2, 0]} scale={[0.35, 0.35, 0.38]} />
        <mesh geometry={nodes.Cube036_0.geometry} material={materials['Material.012']} position={[3.92, -0.88, 0.92]} rotation={[0, -Math.PI / 2, 0]} scale={[0.82, 0.77, 0.82]} />
        <mesh geometry={nodes.Cube033_0.geometry} material={materials['Material.012']} position={[4.01, -0.42, 1.36]} rotation={[0, -Math.PI / 2, 0]} scale={[0.99, 0.94, 0.99]} />
        <mesh geometry={nodes.Cube030_0.geometry} material={materials['Material.012']} position={[4.1, 0.1, 1.6]} rotation={[0, -Math.PI / 2, 0]} scale={[1.11, 0.99, 0.99]} />
        <mesh geometry={nodes.Cube027_0.geometry} material={materials['Material.012']} position={[4.05, 0.66, 1.49]} rotation={[0, -Math.PI / 2, 0]} scale={0.99} />
        <mesh geometry={nodes.Cube025_0.geometry} material={materials['Material.010']} position={[3.94, -0.04, -1.89]} rotation={[0, -Math.PI / 2, 0]} scale={[0.38, 0.38, 0.19]} />
        <mesh geometry={nodes.Cube018_0.geometry} material={materials['Material.012']} position={[3.76, -0.02, -3.94]} rotation={[0, -Math.PI / 2, 0]} scale={0.99} />
        <mesh geometry={nodes.Cube017_0.geometry} material={materials['Material.012']} position={[3.81, -0.01, -4.03]} rotation={[0, -Math.PI / 2, 0]} scale={0.99} />
      </group>
    </group>
  )
}

useGLTF.preload('/hand-transformed.glb')
