/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 helmet.gltf --transform
Author: Andrzej Borkowski (https://sketchfab.com/abg_3d)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/berserk-helmet-1e2d2dc87d3a4ac6b8a7e7bf8453502c
Title: Berserk Helmet
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/helmet-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.visorSupport_low_FinalBaseMesh_default_0.geometry} material={materials.FinalBaseMesh_default} position={[-240.36, 8113.42, 93.93]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.visorSupportDetail1_low_FinalBaseMesh_default_0.geometry} material={materials.FinalBaseMesh_default} position={[-259.27, 8111.11, 55.15]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.visorOutline_low_FinalBaseMesh_default_0.geometry} material={materials.FinalBaseMesh_default} position={[-15.54, 8075.02, 294.8]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.visor_low_FinalBaseMesh_default_0.geometry} material={materials.FinalBaseMesh_default} position={[-15.54, 8072.84, 288.75]} rotation={[-Math.PI, 0, 0]} scale={0.4} />
      <mesh geometry={nodes.nosePiece_low_FinalBaseMesh_default_0.geometry} material={materials.FinalBaseMesh_default} position={[0, 7944.64, 242.98]} />
      <mesh geometry={nodes.mouthPieceBack_low_FinalBaseMesh_default_0.geometry} material={materials.FinalBaseMesh_default} position={[-0.19, 7837.94, 189.49]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.mouthPieceGuard_low_FinalBaseMesh_default_0.geometry} material={materials.FinalBaseMesh_default} position={[-73.73, 7836.11, 201.67]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.subCheeksDetail1_low_FinalBaseMesh_default_0.geometry} material={materials.FinalBaseMesh_default} position={[-102.62, 7850.46, 100.82]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.visorOutline2_low_FinalBaseMesh_default_0.geometry} material={materials.FinalBaseMesh_default} position={[-243.6, 8074.87, 135.38]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.subCheeks_low_FinalBaseMesh_default_0.geometry} material={materials.FinalBaseMesh_default} position={[-102.62, 7850.46, 100.82]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.subCheeksDetail2_low_FinalBaseMesh_default_0.geometry} material={materials.FinalBaseMesh_default} position={[-102.62, 7850.46, 100.82]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.subCheeksDetail2a_low_FinalBaseMesh_default_0.geometry} material={materials.FinalBaseMesh_default} position={[-198.29, 7897.69, 154.26]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.chinPiece_low_FinalBaseMesh_default_0.geometry} material={materials.FinalBaseMesh_default} position={[-18.01, 0, 106.39]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.topPieceMain3_low_FinalBaseMesh_default_0.geometry} material={materials.FinalBaseMesh_default} position={[-98.29, 8370.84, 109]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.topPieceMain_low_FinalBaseMesh_default_0.geometry} material={materials.FinalBaseMesh_default} position={[-122.97, 8395.28, -37.26]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.topPieceMain4_low_FinalBaseMesh_default_0.geometry} material={materials.FinalBaseMesh_default} position={[-113.45, 8456.67, -15.55]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.topPieceMain2_low_FinalBaseMesh_default_0.geometry} material={materials.FinalBaseMesh_default} position={[-36.82, 8481.37, 49.22]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.topPieceDetail1_low_FinalBaseMesh_default_0.geometry} material={materials.FinalBaseMesh_default} position={[-179.02, 8299.91, 130.07]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.topPieceDetail2_low_FinalBaseMesh_default_0.geometry} material={materials.FinalBaseMesh_default} position={[-184.02, 8306.68, 103.8]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.topPieceDetail4_low_FinalBaseMesh_default_0.geometry} material={materials.FinalBaseMesh_default} position={[-156.41, 8272.24, 97.2]} rotation={[-0.65, -0.59, -0.4]} scale={0.22} />
      <mesh geometry={nodes.topPieceDetailSphere_low_FinalBaseMesh_default_0.geometry} material={materials.FinalBaseMesh_default} position={[-189.89, 8302.44, 137.59]} rotation={[-0.64, -0.58, -0.44]} scale={1.62} />
      <mesh geometry={nodes.topPieceDetail5_low_FinalBaseMesh_default_0.geometry} material={materials.FinalBaseMesh_default} position={[-170.81, 8308.75, 131.07]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.topPieceDetail6_low_FinalBaseMesh_default_0.geometry} material={materials.FinalBaseMesh_default} position={[-165.25, 8302.76, 136.89]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.topPieceMainPipe_low_FinalBaseMesh_default_0.geometry} material={materials.FinalBaseMesh_default} position={[-169.74, 8493.51, 36.48]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.topPieceDetail6_low_FinalBaseMesh_default_0_1.geometry} material={materials.FinalBaseMesh_default} position={[-184.02, 8306.68, 103.8]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.topPieceDetail7_low_FinalBaseMesh_default_0.geometry} material={materials.FinalBaseMesh_default} position={[178.53, 8290.29, 115.85]} rotation={[-Math.PI / 2, 0, 0]} scale={0.75} />
      <mesh geometry={nodes.topPieceMainPipe2_low_FinalBaseMesh_default_0.geometry} material={materials.FinalBaseMesh_default} position={[-166.96, 8521.1, -77.13]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.slot_low_FinalBaseMesh_default_0.geometry} material={materials.FinalBaseMesh_default} position={[-16.79, 8081.38, -561.75]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.inside_low_FinalBaseMesh_default_0.geometry} material={materials.FinalBaseMesh_default} position={[0, 8007.82, -172.32]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.topPieceMainPipe3_low_FinalBaseMesh_default_0.geometry} material={materials.FinalBaseMesh_default} position={[-178.11, 8520.17, -82.86]} rotation={[-1.13, -0.52, 0.34]} scale={0.2} />
      <mesh geometry={nodes.topPieceMainPipe4_low_FinalBaseMesh_default_0.geometry} material={materials.FinalBaseMesh_default} position={[-153.66, 8521.74, -71.76]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.topPieceMain4_low_FinalBaseMesh_default_0_1.geometry} material={materials.FinalBaseMesh_default} position={[-139.22, 8147.41, -459.52]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.topPieceMain5_low_FinalBaseMesh_default_0.geometry} material={materials.FinalBaseMesh_default} position={[-139.22, 8147.41, -459.52]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.topPieceMain3Detail2_low_FinalBaseMesh_default_0.geometry} material={materials.FinalBaseMesh_default} position={[-276.63, 8166.01, -438.7]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.topPieceMain2_low_FinalBaseMesh_default_0_1.geometry} material={materials.FinalBaseMesh_default} position={[150.37, 8243.35, -471.51]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.backPiece1Detal_low_FinalBaseMesh_default_0.geometry} material={materials.FinalBaseMesh_default} position={[-147.73, 8277.84, -404.13]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.earphoneCable1_low_FinalBaseMesh_default_0.geometry} material={materials.FinalBaseMesh_default} position={[-291.63, 8117.38, -271.86]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.sidePiece2_low_FinalBaseMesh_default_0.geometry} material={materials.FinalBaseMesh_default} position={[-161.1, 8108.71, -183.21]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.earphone_low_FinalBaseMesh_default_0.geometry} material={materials.FinalBaseMesh_default} position={[-281.86, 8116.52, -240.85]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={0.44} />
      <mesh geometry={nodes.earphoneDetail_low_FinalBaseMesh_default_0.geometry} material={materials.FinalBaseMesh_default} position={[-322.6, 8181.07, -263.67]} rotation={[-1.57, 0, 0]} />
      <mesh geometry={nodes.earphoneCable3_low_FinalBaseMesh_default_0.geometry} material={materials.FinalBaseMesh_default} position={[-296.68, 8086.76, -285.65]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.earphoneCable2_low_FinalBaseMesh_default_0.geometry} material={materials.FinalBaseMesh_default} position={[-283.77, 8084.93, -236.95]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.earphoneLightSrc_low_FinalBaseMesh_default_0.geometry} material={materials.FinalBaseMesh_default} position={[-267, 8099.63, -259.87]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={1.67} />
      <mesh geometry={nodes.backPiece1_low_FinalBaseMesh_default_0.geometry} material={materials.FinalBaseMesh_default} position={[-147.73, 8277.84, -404.13]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.topPieceMain33_low_FinalBaseMesh_default_0.geometry} material={materials.FinalBaseMesh_default} position={[-139.22, 8147.41, -459.52]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.backNeckPiece_low_FinalBaseMesh_default_0.geometry} material={materials.FinalBaseMesh_default} position={[-170.4, 7999.68, -189.21]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.backNeckPiece2_low_FinalBaseMesh_default_0.geometry} material={materials.FinalBaseMesh_default} position={[-170.4, 8027.36, -215.31]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.sidePiece_low_FinalBaseMesh_default_0.geometry} material={materials.FinalBaseMesh_default} position={[-161.1, 8108.71, -183.21]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.sidePieceVent_low_FinalBaseMesh_default_0.geometry} material={materials.FinalBaseMesh_default} position={[-198.94, 8427.83, -377.06]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.earphoneDetail_FinalBaseMesh_default_0.geometry} material={materials.FinalBaseMesh_default} position={[-322.6, 8170.88, -225.72]} rotation={[-1.05, 0, 0]} />
      <mesh geometry={nodes.earphoneDetail_FinalBaseMesh_default_0_1.geometry} material={materials.FinalBaseMesh_default} position={[-322.6, 8143.09, -197.94]} rotation={[-0.52, 0, 0]} />
      <mesh geometry={nodes.earphoneDetail_FinalBaseMesh_default_0_2.geometry} material={materials.FinalBaseMesh_default} position={[-322.6, 8105.13, -187.78]} />
      <mesh geometry={nodes.earphoneDetail_FinalBaseMesh_default_0_3.geometry} material={materials.FinalBaseMesh_default} position={[-322.6, 8067.17, -197.97]} rotation={[0.52, 0, 0]} />
      <mesh geometry={nodes.earphoneDetail_FinalBaseMesh_default_0_4.geometry} material={materials.FinalBaseMesh_default} position={[-322.6, 8039.4, -225.76]} rotation={[1.05, 0, 0]} />
      <mesh geometry={nodes.earphoneDetail_FinalBaseMesh_default_0_5.geometry} material={materials.FinalBaseMesh_default} position={[-322.6, 8029.24, -263.72]} rotation={[1.57, 0, 0]} />
      <mesh geometry={nodes.earphoneDetail_FinalBaseMesh_default_0_6.geometry} material={materials.FinalBaseMesh_default} position={[-322.6, 8039.43, -301.67]} rotation={[2.09, 0, 0]} />
      <mesh geometry={nodes.earphoneDetail_FinalBaseMesh_default_0_7.geometry} material={materials.FinalBaseMesh_default} position={[-322.6, 8067.22, -329.45]} rotation={[2.62, 0, 0]} />
      <mesh geometry={nodes.earphoneDetail_FinalBaseMesh_default_0_8.geometry} material={materials.FinalBaseMesh_default} position={[-322.6, 8105.18, -339.61]} rotation={[-3.14, 0, 0]} />
      <mesh geometry={nodes.earphoneDetail_FinalBaseMesh_default_0_9.geometry} material={materials.FinalBaseMesh_default} position={[-322.6, 8143.13, -329.42]} rotation={[-2.62, 0, 0]} />
      <mesh geometry={nodes.earphoneDetail_FinalBaseMesh_default_0_10.geometry} material={materials.FinalBaseMesh_default} position={[-322.6, 8170.91, -301.63]} rotation={[-2.09, 0, 0]} />
      <mesh geometry={nodes.earphoneDetail_FinalBaseMesh_default_0_11.geometry} material={materials.FinalBaseMesh_default} position={[324.84, 8181.07, -263.72]} rotation={[-1.57, 0, -Math.PI]} />
      <mesh geometry={nodes.earphoneDetail_FinalBaseMesh_default_0_12.geometry} material={materials.FinalBaseMesh_default} position={[324.84, 8170.88, -301.67]} rotation={[-2.09, 0, -Math.PI]} />
      <mesh geometry={nodes.earphoneDetail_FinalBaseMesh_default_0_13.geometry} material={materials.FinalBaseMesh_default} position={[324.84, 8143.09, -329.45]} rotation={[-2.62, 0, -Math.PI]} />
      <mesh geometry={nodes.earphoneDetail_FinalBaseMesh_default_0_14.geometry} material={materials.FinalBaseMesh_default} position={[324.84, 8105.13, -339.61]} rotation={[3.14, 0, Math.PI]} />
      <mesh geometry={nodes.earphoneDetail_FinalBaseMesh_default_0_15.geometry} material={materials.FinalBaseMesh_default} position={[324.84, 8067.17, -329.42]} rotation={[2.62, 0, Math.PI]} />
      <mesh geometry={nodes.earphoneDetail_FinalBaseMesh_default_0_16.geometry} material={materials.FinalBaseMesh_default} position={[324.84, 8039.4, -301.63]} rotation={[2.09, 0, Math.PI]} />
      <mesh geometry={nodes.earphoneDetail_FinalBaseMesh_default_0_17.geometry} material={materials.FinalBaseMesh_default} position={[324.84, 8029.24, -263.67]} rotation={[1.57, 0, Math.PI]} />
      <mesh geometry={nodes.earphoneDetail_FinalBaseMesh_default_0_18.geometry} material={materials.FinalBaseMesh_default} position={[324.84, 8039.43, -225.72]} rotation={[1.05, 0, Math.PI]} />
      <mesh geometry={nodes.earphoneDetail_FinalBaseMesh_default_0_19.geometry} material={materials.FinalBaseMesh_default} position={[324.84, 8067.22, -197.94]} rotation={[0.52, 0, Math.PI]} />
      <mesh geometry={nodes.earphoneDetail_FinalBaseMesh_default_0_20.geometry} material={materials.FinalBaseMesh_default} position={[324.84, 8105.18, -187.78]} rotation={[0, 0, -Math.PI]} />
      <mesh geometry={nodes.earphoneDetail_FinalBaseMesh_default_0_21.geometry} material={materials.FinalBaseMesh_default} position={[324.84, 8143.13, -197.97]} rotation={[-0.52, 0, -Math.PI]} />
      <mesh geometry={nodes.earphoneDetail_FinalBaseMesh_default_0_22.geometry} material={materials.FinalBaseMesh_default} position={[324.84, 8170.91, -225.76]} rotation={[-1.05, 0, -Math.PI]} />
      <mesh geometry={nodes.earphoneCable1_FinalBaseMesh_default_0.geometry} material={materials.FinalBaseMesh_default} position={[296.67, 8118.86, -266.39]} rotation={[-1.51, -0.49, -2.55]} scale={0.96} />
      <mesh geometry={nodes.earphoneCable3_FinalBaseMesh_default_0.geometry} material={materials.FinalBaseMesh_default} position={[308.01, 8086.76, -285.65]} rotation={[-0.44, 0, Math.PI]} scale={0.92} />
      <mesh geometry={nodes.earphoneLightSrc_FinalBaseMesh_default_0.geometry} material={materials.FinalBaseMesh_default} position={[267.16, 8099.63, -259.87]} rotation={[0, -Math.PI / 2, 0]} scale={1.67} />
    </group>
  )
}

useGLTF.preload('/helmet-transformed.glb')
