/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 porshe.gltf --transform
Author: goobee550 (https://sketchfab.com/goobee550)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/porshe-taycan-c6004141452e4d3ab048bf0fee52666d
Title: Porshe Taycan
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/porshe-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[0, -104.89, -203.05]} rotation={[-0.93, 0, 0]}>
          <mesh geometry={nodes.polySurface1597_Rubber1_0.geometry} material={materials.Rubber1} />
          <mesh geometry={nodes.polySurface1597_Rubber1_0_1.geometry} material={materials.Rubber1} />
          <mesh geometry={nodes.polySurface1597_Rubber1_0_2.geometry} material={materials.Rubber1} />
          <mesh geometry={nodes.polySurface1597_Rubber1_0_3.geometry} material={materials.Rubber1} />
          <mesh geometry={nodes.polySurface1597_Rubber1_0_4.geometry} material={materials.Rubber1} />
          <mesh geometry={nodes.polySurface1597_Rubber1_0_5.geometry} material={materials.Rubber1} />
          <mesh geometry={nodes.polySurface1597_Rubber1_0_6.geometry} material={materials.Rubber1} />
          <mesh geometry={nodes.polySurface1597_Rubber1_0_7.geometry} material={materials.Rubber1} />
          <mesh geometry={nodes.polySurface1597_Whel_color_black_0.geometry} material={materials.Whel_color_black} />
          <mesh geometry={nodes.polySurface1597_Whel_color_black_0_1.geometry} material={materials.Whel_color_black} />
          <mesh geometry={nodes.polySurface1597_Whel_color_white_0.geometry} material={materials.Whel_color_white} />
          <mesh geometry={nodes.polySurface1597_brake_0.geometry} material={materials.brake} />
          <mesh geometry={nodes.polySurface1597_lambert1_0.geometry} material={materials.lambert1} />
          <mesh geometry={nodes.polySurface1597_whell_metal_0.geometry} material={materials.whell_metal} />
        </group>
        <mesh geometry={nodes.Porsche_base_Mirror_polySurface1034_MIRROR_0.geometry} material={materials.MIRROR} />
        <mesh geometry={nodes.Porsche_base_Mirror_polySurface1034_corpus1_0.geometry} material={materials.corpus1} />
        <mesh geometry={nodes.Porsche_base_Mirror_polySurface1034_Black_plastick1_0.geometry} material={materials.Black_plastick1} />
        <mesh geometry={nodes.Porsche_base_Black_plastick_polySurface1038_Black_plastick1_0.geometry} material={materials.Black_plastick1} />
        <mesh geometry={nodes.Porsche_base_corpus_polySurface1088_corpus1_0.geometry} material={materials.corpus1} />
        <mesh geometry={nodes.Porsche_base_corpus_polySurface1088_Black_plastick1_0.geometry} material={materials.Black_plastick1} />
        <mesh geometry={nodes.Porsche_base_corpus_polySurface1088_Glass_headlight_0.geometry} material={materials.Glass_headlight} />
        <mesh geometry={nodes.group27_polySurface1119_Black_plastick1_0.geometry} material={materials.Black_plastick1} />
        <mesh geometry={nodes.polySurface1359_Headlight_metal1_0.geometry} material={materials.Headlight_metal1} />
        <mesh geometry={nodes.polySurface1359_Black_plastick1_0.geometry} material={materials.Black_plastick1} />
        <mesh geometry={nodes.polySurface1359_headlight_white_color_0.geometry} material={materials.headlight_white_color} />
        <mesh geometry={nodes.polySurface1359_Glass_headlight_0.geometry} material={materials.Glass_headlight} />
        <mesh geometry={nodes.polySurface32_Black_plastick1_0.geometry} material={materials.Black_plastick1} />
        <mesh geometry={nodes.pCube16_SKIN_0.geometry} material={materials.SKIN} position={[-45.73, 46.16, -54.25]} rotation={[1.56, 0, 0]} scale={[0.5, 0.32, 0.12]} />
        <mesh geometry={nodes.polySurface383_corpus1_0.geometry} material={materials.corpus1} />
        <mesh geometry={nodes.polySurface1006_SKIN_0.geometry} material={materials.SKIN} position={[-13.72, 44.53, -103.4]} rotation={[2.93, Math.PI / 2, 0]} scale={[0.55, 0.25, 0.12]} />
        <mesh geometry={nodes.pPlane15_Black_plastick1_0.geometry} material={materials.Black_plastick1} position={[0, 34.22, 219.89]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.polySurface999_Black_plastick1_0.geometry} material={materials.Black_plastick1} position={[0, 17.56, -7.41]} />
        <mesh geometry={nodes.polySurface229_glass2_0.geometry} material={materials.glass2} />
        <mesh geometry={nodes.pPlane32_corpus1_0.geometry} material={materials.corpus1} position={[-0.57, 60.24, -242.07]} rotation={[-1.24, 0, 0]} scale={0.05} />
        <mesh geometry={nodes.pPlane23_Black_plastick1_0.geometry} material={materials.Black_plastick1} position={[0, 8.78, 219.89]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.polySurface53_corpus1_0.geometry} material={materials.corpus1} />
        <mesh geometry={nodes._pCylinder585_Black_metal1_0.geometry} material={materials.Black_metal1} position={[-16.93, 35.89, -75.81]} rotation={[0.53, -0.32, 0.1]} scale={1.06} />
        <mesh geometry={nodes.pCube21_SKIN_0.geometry} material={materials.SKIN} position={[-3.83, 39.74, -85.81]} rotation={[-0.53, 0, 0]} scale={[0.5, 0.56, 0.12]} />
        <mesh geometry={nodes.polySurface157_Black_plastick1_0.geometry} material={materials.Black_plastick1} position={[-0.63, 2.26, 16.64]} scale={0.94} />
        <mesh geometry={nodes.pCube4_Done14_Black_plastick1_0.geometry} material={materials.Black_plastick1} />
        <mesh geometry={nodes.pCube2_Black_plastick1_0.geometry} material={materials.Black_plastick1} position={[81.11, 101.63, 64.96]} rotation={[0, 0, 0.3]} />
        <mesh geometry={nodes.polySurface1005_SKIN_0.geometry} material={materials.SKIN} position={[71.22, 44.53, -103.4]} rotation={[2.93, Math.PI / 2, 0]} scale={[0.55, 0.25, 0.12]} />
        <mesh geometry={nodes.pCube24_SKIN_0.geometry} material={materials.SKIN} position={[-2.99, 46.16, -84.57]} rotation={[1.56, 0, 0]} scale={[0.5, 0.32, 0.12]} />
        <mesh geometry={nodes.polySurface1037_Black_plastick1_0.geometry} material={materials.Black_plastick1} position={[-0.84, 0, 0]} />
        <mesh geometry={nodes.pPlane16_Black_plastick1_0.geometry} material={materials.Black_plastick1} position={[0, 31.04, 219.89]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.pPlane25_Black_plastick1_0.geometry} material={materials.Black_plastick1} />
        <mesh geometry={nodes.polySurface228_Black_glass1_0.geometry} material={materials.Black_glass1} />
        <mesh geometry={nodes.polySurface231_Black_glass1_0.geometry} material={materials.Black_glass1} />
        <mesh geometry={nodes.polySurface380_Glass_headlight_0.geometry} material={materials.Glass_headlight} />
        <mesh geometry={nodes.pCube32_SKIN_0.geometry} material={materials.SKIN} position={[-46.34, 102.72, -118.66]} rotation={[-0.13, 0, 0]} scale={[0.27, 0.22, 0.07]} />
        <mesh geometry={nodes.polySurface232_corpus1_0.geometry} material={materials.corpus1} />
        <mesh geometry={nodes.polySurface216_glass2_0.geometry} material={materials.glass2} />
        <mesh geometry={nodes.polySurface26_Black_plastick1_0.geometry} material={materials.Black_plastick1} />
        <mesh geometry={nodes.polySurface1013_Carbon_black1_0.geometry} material={materials.SKIN} position={[-3.67, 40.69, -17.63]} scale={1.07} />
        <mesh geometry={nodes.polySurface164_Black_plastick1_0.geometry} material={materials.Black_plastick1} />
        <mesh geometry={nodes.polySurface218_Black_plastick1_0.geometry} material={materials.Black_plastick1} />
        <mesh geometry={nodes.polySurface1086_red_headlight_0.geometry} material={materials.red_headlight} position={[0, 0, 0.16]} />
        <mesh geometry={nodes.pSphere3_Black_plastick1_0.geometry} material={materials.Black_plastick1} />
        <mesh geometry={nodes.polySurface966_Potolok1_0.geometry} material={materials.SKIN} position={[0, -220.57, 0]} />
        <mesh geometry={nodes.polySurface83_Black_plastick1_0.geometry} material={materials.Black_plastick1} position={[-259.59, 0, 0]} />
        <mesh geometry={nodes.pCube30_SKIN_0.geometry} material={materials.SKIN} position={[-46.35, 85.93, -114.21]} rotation={[-0.53, 0, 0]} scale={[0.5, 0.41, 0.12]} />
        <mesh geometry={nodes.pCube35_Black_plastick1_0.geometry} material={materials.Black_plastick1} position={[37.59, 32.87, 16.64]} rotation={[-0.05, 0, 0]} scale={[0.23, 0.17, 0.32]} />
        <mesh geometry={nodes.polySurface1087_Black_plastick1_0.geometry} material={materials.Black_plastick1} position={[0, 0, 0.16]} />
        <mesh geometry={nodes.pPlane27_Black_plastick1_0.geometry} material={materials.Black_plastick1} position={[126.41, 44.07, 87.21]} rotation={[-Math.PI / 2, 0, 0]} scale={0.7} />
        <mesh geometry={nodes.polySurface918_corpus1_0.geometry} material={materials.corpus1} />
        <mesh geometry={nodes.polySurface379_Black_glass1_0.geometry} material={materials.Black_glass1} />
        <mesh geometry={nodes.pSphere1_glass_specular_0.geometry} material={materials.glass_specular} position={[-9.86, 35.29, 235.35]} scale={0.04} />
        <mesh geometry={nodes.polySurface1014_Carbon_black1_0.geometry} material={materials.SKIN} position={[-3.67, 40.69, -17.63]} scale={1.07} />
        <mesh geometry={nodes.pPlane17_Black_plastick1_0.geometry} material={materials.Black_plastick1} position={[0, 27.86, 219.89]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.polySurface916_Black_plastick1_0.geometry} material={materials.Black_plastick1} />
        <mesh geometry={nodes.pCube22_SKIN_0.geometry} material={materials.SKIN} position={[42.82, 85.2, -113.76]} rotation={[-0.53, 0, 0]} scale={[0.5, 0.41, 0.12]} />
        <mesh geometry={nodes.pCube33_SKIN_0.geometry} material={materials.SKIN} position={[41.61, 102.17, -118.59]} rotation={[-0.13, 0, 0]} scale={[0.27, 0.22, 0.07]} />
        <mesh geometry={nodes.polySurface940_corpus1_0.geometry} material={materials.corpus1} />
        <mesh geometry={nodes._polySurface86_Black_plastick1_0.geometry} material={materials.Black_plastick1} />
        <mesh geometry={nodes.pCube27_SKIN_0.geometry} material={materials.SKIN} position={[42.52, 46.16, -54.1]} rotation={[1.56, 0, 0]} scale={[0.5, 0.32, 0.12]} />
        <mesh geometry={nodes.pCube36_Black_plastick1_0.geometry} material={materials.Black_plastick1} position={[-4.52, 33.04, -57.54]} rotation={[-0.05, 0, 0]} scale={[0.23, 0.17, 0.32]} />
        <mesh geometry={nodes.polySurface183_Black_plastick1_0.geometry} material={materials.Black_plastick1} />
        <mesh geometry={nodes.polySurface939_corpus1_0.geometry} material={materials.corpus1} />
        <mesh geometry={nodes.polySurface381_corpus1_0.geometry} material={materials.corpus1} />
        <mesh geometry={nodes.polySurface382_corpus1_0.geometry} material={materials.corpus1} />
        <mesh geometry={nodes._pCylinder584_Black_metal1_0.geometry} material={materials.Black_metal1} position={[-35.87, 21.82, -56.61]} rotation={[0.44, 0.18, -0.09]} scale={1.06} />
        <mesh geometry={nodes.pPlane50_Black_plastick1_0.geometry} material={materials.Black_plastick1} position={[82.58, 47.51, 191.46]} rotation={[1.2, -0.13, -0.05]} scale={[0.15, 0.39, 0.39]} />
        <mesh geometry={nodes.polySurface1003_SKIN_0.geometry} material={materials.SKIN} position={[77.29, 63.65, -98.17]} rotation={[-0.53, 0, Math.PI / 2]} scale={[0.55, 0.25, 0.12]} />
        <mesh geometry={nodes.polySurface179_Black_plastick1_0.geometry} material={materials.Black_plastick1} />
        <mesh geometry={nodes.polySurface1019_znack1_0.geometry} material={materials.znack1} position={[-106.37, -12.03, 193.47]} rotation={[1.44, 1.56, -1.04]} scale={1.04} />
        <mesh geometry={nodes.pCube26_SKIN_0.geometry} material={materials.SKIN} position={[42.52, 46.16, -84.57]} rotation={[1.56, 0, 0]} scale={[0.5, 0.32, 0.12]} />
        <mesh geometry={nodes.polySurface63_Black_plastick1_0.geometry} material={materials.Black_plastick1} />
        <mesh geometry={nodes.pPlane14_Black_plastick1_0.geometry} material={materials.Black_plastick1} position={[0, 37.4, 219.89]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.polySurface1036_Carbon_black1_0.geometry} material={materials.SKIN} />
        <mesh geometry={nodes.polySurface220_Black_plastick1_0.geometry} material={materials.Black_plastick1} />
        <mesh geometry={nodes.polySurface1002_Black_plastick1_0.geometry} material={materials.Black_plastick1} />
        <mesh geometry={nodes.pCube14_SKIN_0.geometry} material={materials.SKIN} position={[-45.73, 46.16, -84.57]} rotation={[1.56, 0, 0]} scale={[0.5, 0.32, 0.12]} />
        <mesh geometry={nodes.pPlane13_Black_plastick1_0.geometry} material={materials.Black_plastick1} position={[0, 35.8, 219.91]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.pCube31_SKIN_0.geometry} material={materials.SKIN} position={[-3.03, 85.96, -113.65]} rotation={[-0.53, 0, 0]} scale={[0.5, 0.41, 0.12]} />
        <mesh geometry={nodes.pPlane49_Carbon_black1_0.geometry} material={materials.SKIN} position={[0.53, 63.71, -98.85]} rotation={[1.13, -0.01, 0]} />
        <mesh geometry={nodes.pCube19_SKIN_0.geometry} material={materials.SKIN} position={[40.63, 39.35, -85.58]} rotation={[-0.53, 0, 0]} scale={[0.5, 0.56, 0.12]} />
        <mesh geometry={nodes.polySurface30_Black_plastick1_0.geometry} material={materials.Black_plastick1} position={[0, 0, -3.02]} />
        <mesh geometry={nodes.polySurface1004_SKIN_0.geometry} material={materials.SKIN} position={[-6.27, 63.65, -98.17]} rotation={[-0.53, 0, Math.PI / 2]} scale={[0.55, 0.25, 0.12]} />
        <mesh geometry={nodes.pPlane47_White_plastick1_0.geometry} material={materials.White_plastick1} position={[-102.38, 47.3, -182.35]} rotation={[0.76, 0, 0]} scale={0.25} />
        <mesh geometry={nodes.polySurface929_Black_plastick1_0.geometry} material={materials.Black_plastick1} position={[13.46, 82.78, -236.6]} rotation={[-0.56, 0, 0]} scale={0.14} />
        <mesh geometry={nodes.pCube25_SKIN_0.geometry} material={materials.SKIN} position={[-2.99, 46.16, -54.09]} rotation={[1.56, 0, 0]} scale={[0.5, 0.32, 0.12]} />
        <mesh geometry={nodes.pCube28_SKIN_0.geometry} material={materials.SKIN} position={[-3.68, 103.08, -118.71]} rotation={[-0.13, 0, 0]} scale={[0.27, 0.22, 0.07]} />
        <mesh geometry={nodes.polySurface161_Black_plastick1_0.geometry} material={materials.Black_plastick1} position={[0, 0, -5.53]} />
        <mesh geometry={nodes.polySurface1112_MIRROR_0.geometry} material={materials.MIRROR} position={[0, 11.82, 2.39]} scale={[1.28, 0.9, 1]} />
        <mesh geometry={nodes.polySurface158_Black_plastick1_0.geometry} material={materials.Black_plastick1} />
        <mesh geometry={nodes.polySurface1016_Carbon_black1_0.geometry} material={materials.SKIN} position={[-3.67, 40.69, -17.63]} scale={1.07} />
        <mesh geometry={nodes.polySurface377_corpus1_0.geometry} material={materials.corpus1} />
        <mesh geometry={nodes.pCube34_Carbon_black1_0.geometry} material={materials.SKIN} position={[-2.81, 46.4, 6.56]} />
        <mesh geometry={nodes.polySurface217_glass2_0.geometry} material={materials.glass2} />
        <mesh geometry={nodes.polySurface1012_Carbon_black1_0.geometry} material={materials.SKIN} position={[-3.67, 40.69, -17.63]} scale={1.07} />
        <mesh geometry={nodes.pCube37_Black_plastick1_0.geometry} material={materials.Black_plastick1} position={[-47.64, 32.87, 16.64]} rotation={[-0.05, 0, 0]} scale={[0.23, 0.17, 0.32]} />
        <mesh geometry={nodes.polySurface230_glass2_0.geometry} material={materials.glass2} />
        <mesh geometry={nodes.polySurface1035_Carbon_black1_0.geometry} material={materials.SKIN} />
        <mesh geometry={nodes.polySurface1113_SKIN_0.geometry} material={materials.SKIN} position={[-85.24, 0, 0]} />
        <mesh geometry={nodes.polySurface106group5_Black_plastick1_0.geometry} material={materials.Black_plastick1} />
        <mesh geometry={nodes.polySurface1011_Carbon_black1_0.geometry} material={materials.SKIN} position={[-3.67, 40.69, -17.63]} scale={1.07} />
        <mesh geometry={nodes.polySurface233_corpus1_0.geometry} material={materials.corpus1} />
        <mesh geometry={nodes.polySurface891_corpus1_0.geometry} material={materials.corpus1} />
        <mesh geometry={nodes.polySurface43_Black_plastick1_0.geometry} material={materials.Black_plastick1} position={[0, 1.84, -8.03]} />
        <mesh geometry={nodes.polySurface378_corpus1_0.geometry} material={materials.corpus1} />
        <mesh geometry={nodes.polySurface920_corpus1_0.geometry} material={materials.corpus1} />
        <mesh geometry={nodes.polySurface1029_SKIN_0.geometry} material={materials.SKIN} />
        <mesh geometry={nodes.polySurface108_Black_plastick1_0.geometry} material={materials.Black_plastick1} />
        <mesh geometry={nodes.polySurface169_Black_plastick1_0.geometry} material={materials.Black_plastick1} />
        <mesh geometry={nodes.polySurface1111_Black_plastick1_0.geometry} material={materials.Black_plastick1} position={[0, 11.82, 2.39]} scale={[1.28, 0.9, 1]} />
        <mesh geometry={nodes.polySurface903_znack1_0.geometry} material={materials.znack1} position={[204.23, -152.49, 192.23]} rotation={[0.35, -1.54, Math.PI / 2]} scale={1.36} />
        <mesh geometry={nodes.polySurface971_Carbon_black1_0.geometry} material={materials.SKIN} />
        <mesh geometry={nodes.pCube10_SKIN_0.geometry} material={materials.SKIN} position={[-45.19, 40.06, -86]} rotation={[-0.53, 0, 0]} scale={[0.5, 0.56, 0.12]} />
        <mesh geometry={nodes.polySurface1015_Carbon_black1_0.geometry} material={materials.SKIN} position={[-3.67, 40.69, -17.63]} scale={1.07} />
        <mesh geometry={nodes.polySurface215_glass2_0.geometry} material={materials.glass2} />
        <mesh geometry={nodes.polySurface214_Black_plastick1_0.geometry} material={materials.Black_plastick1} />
        <mesh geometry={nodes.polySurface1017_Carbon_black1_0.geometry} material={materials.SKIN} position={[-3.67, 40.69, -12.58]} scale={1.07} />
        <mesh geometry={nodes.polySurface895_corpus1_0.geometry} material={materials.corpus1} />
        <mesh geometry={nodes.polySurface1596_znack1_0.geometry} material={materials.znack1} position={[0.13, 0, -291.3]} />
        <mesh geometry={nodes.polySurface1534_Rubber1_0.geometry} material={materials.Rubber1} />
        <mesh geometry={nodes.polySurface1534_Rubber1_0_1.geometry} material={materials.Rubber1} />
        <mesh geometry={nodes.polySurface1534_Rubber1_0_2.geometry} material={materials.Rubber1} />
        <mesh geometry={nodes.polySurface1534_Rubber1_0_3.geometry} material={materials.Rubber1} />
        <mesh geometry={nodes.polySurface1534_Rubber1_0_4.geometry} material={materials.Rubber1} />
        <mesh geometry={nodes.polySurface1534_Rubber1_0_5.geometry} material={materials.Rubber1} />
        <mesh geometry={nodes.polySurface1534_Rubber1_0_6.geometry} material={materials.Rubber1} />
        <mesh geometry={nodes.polySurface1534_Rubber1_0_7.geometry} material={materials.Rubber1} />
        <mesh geometry={nodes.polySurface1534_Whel_color_black_0.geometry} material={materials.Whel_color_black} />
        <mesh geometry={nodes.polySurface1534_Whel_color_black_0_1.geometry} material={materials.Whel_color_black} />
        <mesh geometry={nodes.polySurface1534_Whel_color_white_0.geometry} material={materials.Whel_color_white} />
        <mesh geometry={nodes.polySurface1534_brake_0.geometry} material={materials.brake} />
        <mesh geometry={nodes.polySurface1534_lambert1_0.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.polySurface1534_whell_metal_0.geometry} material={materials.whell_metal} />
        <mesh geometry={nodes.polySurface1598_znack1_0.geometry} material={materials.znack1} position={[0.13, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/porshe-transformed.glb')
